### PR TITLE
Fix align center

### PR DESCRIPTION
**Pull request by revolunet**
thanks for this widget ! 

when the switch container was left centered, it was also applied to the switch contents; 

this fix force left alignement on the switch itself.

before :
capture d ecran 2018-06-13 a 23 53 48

after :
capture d ecran 2018-06-13 a 23 53 59

also after this "security" issue :
capture d ecran 2018-06-13 a 23 44 21

i updated the webpack dependency, tests and build runs 👌
capture d ecran 2018-06-13 a 23 52 23

### CODE REVIEW

**Comment by markusenglund** [comment]
CSS never fails to surprise me :upside_down_face: 

Good fix. I wanna merge, but could you remove the example you added to the demo page first? I don't think it's necessary to showcase a centered switch to others.

**Comment by revolunet** [comment]
yeah... "cascading"...

should be good now :)

**Comment by markusenglund** [comment]
I'm working on another small change to the package so I'll until I've finished that to publish this to npm.

**Comment by revolunet** [comment]
great, thanks !

**Pull request merged**
