### PR TITLE
Add handle icons

### LINKED ISSUE #55: Customise Option For Handler
Can we add icon inside handler ? 

E.g

image

Thanks

### LINKED ISSUE #57: Can we somehow add image to the round toggle switch?
As per my UI design, I want to customise the toggle switch. Is there a way to do that?
Any help will be appreciated. Thanks

toggle

### PR DESCRIPTION
**Pull request by morinted**
Fix #55, Fix #57 

I saw that there were already a couple issues open for this, so decided that I would share upstream in case you were interested in this feature.

Adds two props, uncheckedHandleIcon and checkedHandleIcon. When provided, the handle will render with an icon on it.

handle icons demo

Things I've done in this PR:

- Add the feature
- Update TypeScript bindings
- Update read me
- Update demo
- Add "prepare" property of package.json—this allows installing via npm directly through GitHub and will add a build step on publish automatically.

Hope this is helpful!

### CODE REVIEW

**Comment by princesinha19** [comment]
@morinted Good PR. @markusenglund Please merge it.

**Comment by VirtualParticle** [comment]
This is great, this would be really useful for something like a night mode toggle.

**Comment by quolpr** [comment]
@markusenglund what do you think?

**Comment by markusenglund** [comment]
Hi, I'm sorry for the late response.

The PR is excellent, no problems found. The feature seems to be of interest to a lot people so it will be a good addition to the package. It will be included in the next release which should be out before new year.

**Pull request merged**
